---
title: "Tangle Bearing Neurons Viewer"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r global, include = FALSE}
#    This file is part of tangle-bearing-neurons.
#    Copyright (C) 2024  Emir Turkes, UK DRI at UCL
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Emir Turkes can be contacted at emir.turkes@eturkes.com

library(conflicted)
conflicts_prefer(igraph::degree, base::intersect, DT::JS, graphics::layout)
library(scales)
library(InteractiveComplexHeatmap)
library(circlize)
library(GSEABase)
library(reshape2)
library(dplyr)
library(igraph)
library(qgraph)
library(visNetwork)
library(purrr)
library(networkD3)
library(DT)
library(tidyr)
library(ggplot2)
library(plotly)
library(scuttle)
library(flextable)
library(eulerr)
library(RColorBrewer)

`%notin%` <- Negate(`%in%`)

datatable_download_exp_15 <- function(dt) {
  datatable(
    dt,
    options = list(
      pageLength = 15,
      scrollX = TRUE,
      dom = "Blfrtip",
      buttons = list(
        "copy", "print",
        list(
          extend = "collection", buttons = c("csv", "excel", "pdf"),
          text = "Download"
        )
      ),
      rowCallback = JS(
        "function(row, data) {",
        "for (i = 1; i < data.length; i++) {",
        "if (data[i]>=1000 | data[i]<1000) {",
        "$('td:eq('+i+')', row).html(data[i].toExponential(2));}}}"
      )
    ),
    extensions = "Buttons"
  )
}

network_filt <- function(thresh, weight = 0.25) {
  out1 <- 0.5 + (weight * (thresh - 0.5))
  out2 <- 0.5 - (weight * (thresh - 0.5))
  list(out1 = out1, out2 = out2)
}

scale_range <- function(x, from = c(1, 45), to = c(8, 16)) {
  to[1] + (from[2] - x) * diff(to) / diff(from)
}

map_range <- function (x) {
  ifelse(
    x <= 0.3, yes = 1, no = ifelse(x >= 0.7, yes = 4, no = round(1 + x * 3))
  )
}

add_newline <- function(string) {
  words <- strsplit(string, split = " ")[[1]]
  chunks <- split(words, f = ceiling(seq_along(words) / 2))
  paste(sapply(chunks, FUN = paste, collapse = " "), collapse = "\n")
}

data_sets <- c(
  "LCM Mass Spec - Human AD BA9 - Single-cell",
  "LCM Mass Spectrometry - Human AD BA9",
  "FACS-sorted ssRNAseq - Human AD BA9"
)
data_types <- c(
  "log2 LFQ Intensity", "log2 LFQ Intensity", "log2 CPM",
  "log2 Enrichment Score", "log2 Enrichment Score", "log2 Enrichment Score"
)

data_dir <- file.path("..", "data")
cache_dir <- file.path("..", "cache")
if (!dir.exists(cache_dir)) {
  dir.create(cache_dir, recursive = TRUE)
}

gene_sets <- readRDS(file.path(data_dir, "gene_sets.rds"))
gene_anno <- readRDS(file.path(data_dir, "gene_anno.rds"))
map <- setNames(gene_anno$symbol, gene_anno$ensembl)

meta <- vector("list", length = length(data_sets))
deg <- vector("list", length = length(data_sets))
gse <- vector("list", length = length(data_sets))
res_deg <- vector("list", length = length(data_sets))
res_gse <- vector("list", length = length(data_sets))
res_gse_fmt <- vector("list", length = length(data_sets))

data_dir <- list.dirs(data_dir)
data_dir <- data_dir[c(2, 3, 4)]
for (i in seq_along(data_sets)) {
  meta[[i]] <- readRDS(file.path(data_dir[i], "meta.rds"))
  deg[[i]] <- readRDS(file.path(data_dir[i], "deg.rds"))
  gse[[i]] <- readRDS(file.path(data_dir[i], "gse.rds"))
  res_deg[[i]] <- readRDS(file.path(data_dir[i], "res_deg.rds"))
  res_gse[[i]] <- readRDS(file.path(data_dir[i], "res_gse.rds"))

  res_gse_fmt[[i]] <- res_gse[[i]]
  gene_sets_sub <- gene_sets[names(gene_sets) %in% rownames(res_gse_fmt[[i]])]
  gene_sets_sub <- gene_sets_sub[
    match(rownames(res_gse_fmt[[i]]), names(gene_sets_sub))
  ]
  id <- c()
  for (j in seq_along(gene_sets_sub)) {
    id <- c(id, gene_sets[[j]]@shortDescription)
  }
  rownames(res_gse_fmt[[i]]) <- id
  res_gse_fmt[[i]] <- res_gse_fmt[[i]][ , c(6, 1:5)]
}

top_anno <- vector("list", length = length(data_sets))
for (i in seq_along(data_sets)) {
  n <- length(unique(meta[[i]]$donor))
  anno_colour <- hue_pal()(n)
  top_anno[[i]] <- HeatmapAnnotation(
    Donor = meta[[i]]$donor,
    group = anno_block(
      gp = gpar(fill = "lightgray", col = "lightgray"),
      labels = unique(meta[[i]]$tau),
      labels_gp = gpar(col = "black", fontsize = 14),
      height = unit(6, "mm")
    ),
    col = list(Donor = setNames(anno_colour, unique(meta[[i]]$donor))),
    simple_anno_size = unit(4, "mm"),
    show_legend = c("Donor" = FALSE),
    annotation_name_gp = gpar(fontsize = 12)
  )
}

p_adj <- p.adjust(
  unlist(c(lapply(res_deg, `[[`, "P.value"), lapply(res_gse, `[[`, "P.value"))),
  method = "BH"
)
p_adj <- split(
  p_adj,
  f = rep(
    seq_along(c(res_deg, res_gse)),
    times = sapply(c(res_deg, res_gse), FUN = nrow)
  )
)
for (i in seq_along(res_deg)) {
  res_deg[[i]]$P.value.adj <- p_adj[[i]]
}
for (i in seq_along(res_gse)) {
  res_gse[[i]]$P.value.adj <- p_adj[[i + length(data_sets)]]
}

hubs <- vector("list", length = length(data_sets))
hubs[[2]] <- c(
  "NEFM", "APP", "SQSTM1", "HSP90AA1", "YWHAE", "WASF1", "CNTNAP1", "GOT2"
)
hubs[[3]] <- c(
  "NEFM", "APP", "SQSTM1", "HSP90AA1", "YWHAE", "WASF1", "CNTNAP1", "GOT2"
)

priority_gse <- vector("list", length = length(data_sets))
priority_gse[[1]] <- NULL
priority_gse[[2]] <- list(
  `NEFM Associated` = "NEFM",
  `APP Associated` = "APP",
  `SQSTM1 Associated` = "SQSTM1",
  `HSP90AA1 Associated` = "HSP90AA1",
  `YWHAE Associated` = "YWHAE",
  `WASF1 Associated` = "WASF1",
  `CNTNAP1 Associated` = "CNTNAP1",
  `GOT2 Associated`= "GOT2"
)
priority_gse[[3]] <- list(
  `NEFM Associated` = "NEFM",
  `APP Associated` = "APP",
  `SQSTM1 Associated` = "SQSTM1",
  `HSP90AA1 Associated` = "HSP90AA1",
  `YWHAE Associated` = "YWHAE",
  `WASF1 Associated` = "WASF1",
  `CNTNAP1 Associated` = "CNTNAP1",
  `GOT2 Associated`= "GOT2"
)

for (i in seq_along(priority_gse)) {
  for (j in seq_along(priority_gse[[i]])) {
    gene_anno_sub <- gene_anno[gene_anno$symbol %in% priority_gse[[i]][[j]], ]
    keep <- which(
      sapply(
        geneIds(gene_sets), FUN = function(x) any(x %in% gene_anno_sub$ensembl)
      )
    )
    priority_gse[[i]][[j]] <- names(keep)
  }
}


if (file.exists(file.path(cache_dir, "range_gse.rds"))) {
  range_gse <- readRDS(file.path(cache_dir, "range_gse.rds"))
  sig_gse <- readRDS(file.path(cache_dir, "sig_gse.rds"))
  top_gse <- readRDS(file.path(cache_dir, "top_gse.rds"))
  range_deg <- readRDS(file.path(cache_dir, "range_deg.rds"))
  sig_deg <- readRDS(file.path(cache_dir, "sig_deg.rds"))
  top_deg <- readRDS(file.path(cache_dir, "top_deg.rds"))
  pseudobulk_deg <- readRDS(file.path(cache_dir, "pseudobulk_deg.rds"))
} else {

  range_gse <- vector("list", length = length(data_sets))
  sig_gse <- vector("list", length = length(data_sets))
  top_gse <- vector("list", length = length(data_sets))
  n_gse <- vector("list", length = length(data_sets))
  pseudobulk_deg <- vector("list", length = length(data_sets))

  for (i in seq_along(data_sets)) {

    range_gse[[i]] <- c(
      min(gse[[i]]), (min(gse[[i]]) + max(gse[[i]])) / 2, max(gse[[i]])
    )

    sig <- ifelse(res_gse[[i]]$P.value.adj < 0.05, yes = 1, no = 0)
    direction <- ifelse(res_gse[[i]]$Coef > 0, yes = 1, no = -1)
    sig <- sig * direction

    names(sig) <- rownames(res_gse[[i]])
    sig <- sig[c(which(sig == 1), which(sig == -1), which(sig == 0))]
    sig <- ifelse(
      sig == -1, yes = "↓", no = ifelse(sig == 1, yes = "↑", no = "")
    )

    sig <- data.frame(CTRL = rep("", times = length(sig)), NFT = sig)
    sig_gse[[i]] <- vector("list", length = 2)
    for (j in seq_along(sig)) {
      sig_gse[[i]][[j]] <- replicate(nrow(meta[[i]]) / 2, expr = sig[ , j])
    }
    sig_gse[[i]] <- do.call(cbind, args = sig_gse[[i]])

    res_gse[[i]] <- res_gse[[i]][match(rownames(sig), rownames(res_gse[[i]])), ]
    rownames(sig_gse[[i]]) <- res_gse[[i]]$GeneSet

    top_gse[[i]] <- sapply(
      priority_gse[[i]],
      function (x) {
        patterns <- x
        matches <- sapply(
          patterns, function(y) {
            grep(
              paste0("\\b", y, "\\b"),
              rownames(res_gse[[i]][res_gse[[i]]$P.value.adj < 0.05, ]),
              value = TRUE
            )
          }
        )
        unique(unlist(matches))
      }
    )

    top_gse[[i]]$`Other Significant` <-
      rownames(res_gse[[i]][res_gse[[i]]$P.value.adj < 0.05, ])[
        rownames(res_gse[[i]][res_gse[[i]]$P.value.adj < 0.05, ]) %notin%
          unlist(top_gse[[i]])
      ]
    top_gse[[i]]$`All Pathways` <- rownames(res_gse[[i]])
  }

  range_deg <- vector("list", length = length(data_sets))
  sig_deg <- vector("list", length = length(data_sets))
  top_deg <- vector("list", length = length(data_sets))
  n_deg <- vector("list", length = length(data_sets))

  for (i in seq_along(data_sets)) {

    range_deg[[i]] <- c(
      min(deg[[i]]), (min(deg[[i]]) + max(deg[[i]])) / 2, max(deg[[i]])
    )

    sig <- ifelse(res_deg[[i]]$P.value.adj < 0.05, yes = 1, no = 0)
    direction <- ifelse(res_deg[[i]]$Coef > 0, yes = 1, no = -1)
    sig <- sig * direction

    names(sig) <- rownames(res_deg[[i]])
    sig <- sig[c(which(sig == 1), which(sig == -1), which(sig == 0))]
    sig <- ifelse(
      sig == -1, yes = "↓", no = ifelse(sig == 1, yes = "↑", no = "")
    )

    sig <- data.frame(CTRL = rep("", times = length(sig)), NFT = sig)
    sig_deg[[i]] <- vector("list", length = 2)
    for (j in seq_along(sig)) {
      sig_deg[[i]][[j]] <- replicate(nrow(meta[[i]]) / 2, expr = sig[ , j])
    }
    sig_deg[[i]] <- do.call(cbind, args = sig_deg[[i]])

    res_deg[[i]] <- res_deg[[i]][match(rownames(sig), rownames(res_deg[[i]])), ]
    rownames(sig_deg[[i]]) <- res_deg[[i]]$Gene

    top_deg[[i]] <- res_deg[[i]][res_deg[[i]]$P.value.adj < 0.05, ]$Gene
    n_deg[[i]] <- length(top_deg[[i]])

    pseudobulk_deg[[i]] <- SingleCellExperiment(list(logcounts = deg[[i]]))
    pseudobulk_deg[[i]] <- aggregateAcrossCells(
      pseudobulk_deg[[i]], meta[[i]]$tau,
      use_exprs_values = "logcounts", statistics = "mean"
    )

  }
  saveRDS(range_gse, file = file.path(cache_dir, "range_gse.rds"))
  saveRDS(sig_gse, file = file.path(cache_dir, "sig_gse.rds"))
  saveRDS(top_gse, file = file.path(cache_dir, "top_gse.rds"))
  saveRDS(range_deg, file = file.path(cache_dir, "range_deg.rds"))
  saveRDS(sig_deg, file = file.path(cache_dir, "sig_deg.rds"))
  saveRDS(top_deg, file = file.path(cache_dir, "top_deg.rds"))
  saveRDS(pseudobulk_deg, file = file.path(cache_dir, "pseudobulk_deg.rds"))
}

priority_gse[[1]] <- c(
  priority_gse[[1]], `Other Significant` = NA, `All Pathways` = NA
)
priority_gse[[2]] <- c(
  priority_gse[[2]], `Other Significant` = NA, `All Pathways` = NA
)
priority_gse[[3]] <- c(
  priority_gse[[3]], `Other Significant` = NA, `All Pathways` = NA
)

n_gse <- vector("list", length = length(data_sets))
n_gse_up <- vector("list", length = length(data_sets))
n_gse_dn <- vector("list", length = length(data_sets))
n_deg <- vector("list", length = length(data_sets))
n_deg_up <- vector("list", length = length(data_sets))
n_deg_dn <- vector("list", length = length(data_sets))
for (i in seq_along(n_gse)) {
  n_gse[[i]] <- res_gse[[i]][res_gse[[i]]$P.value.adj < 0.05, ]
  n_gse_up[[i]] <- nrow(n_gse[[i]][n_gse[[i]]$Coef > 0, ])
  n_gse_dn[[i]] <- nrow(n_gse[[i]][n_gse[[i]]$Coef < 0, ])
  n_gse[[i]] <- nrow(n_gse[[i]])
  n_deg[[i]] <- res_deg[[i]][res_deg[[i]]$P.value.adj < 0.05, ]
  n_deg_up[[i]] <- nrow(n_deg[[i]][n_deg[[i]]$Coef > 0, ])
  n_deg_dn[[i]] <- nrow(n_deg[[i]][n_deg[[i]]$Coef < 0, ])
  n_deg[[i]] <- nrow(n_deg[[i]])
}

venn_col <- brewer.pal(3, name = "Pastel2")[1:2]

res <- data.frame(
  a = c("LCM\nMass Spec", "FACS\nssRNAseq"),
  b = c(n_gse[[2]], n_gse[[3]]),
  c = c(n_deg[[2]], n_deg[[3]]),
  d = c(n_gse_up[[2]], n_gse_up[[3]]),
  e = c(n_gse_dn[[2]], n_gse_dn[[3]]),
  f = c(n_deg_up[[2]], n_deg_up[[3]]),
  g = c(n_deg_dn[[2]], n_deg_dn[[3]]),
  h = c(nrow(res_gse[[2]]), nrow(res_gse[[3]])),
  i = c(nrow(res_deg[[2]]), nrow(res_deg[[3]])),
  j = c(
    percent(n_gse[[2]] / nrow(res_gse[[2]])),
    percent(n_gse[[3]] / nrow(res_gse[[3]]))
  ),
  k = c(
    percent(n_deg[[2]] / nrow(res_deg[[2]])),
    percent(n_deg[[3]] / nrow(res_deg[[3]]))
  )
)
colnames(res) <- c(
  "Dataset",
  "Pathway\nSets\nDifferentially Enriched",
  "Genes/Proteins\nDifferential Expressed",
  "Pathway\nSets\nDE UP",
  "Pathway\nSets\nDE DOWN",
  "Genes/Proteins\nDE UP",
  "Genes/Proteins\nDE DOWN",
  "Pathway\nSets\nTested",
  "Genes/Proteins\nTested",
  "Percentage\nPathway\nSets\nDE",
  "Percentage\nGenes/Proteins\nDE"
)

venn_list_gse <- vector("list", length = 2)
names(venn_list_gse) <- res$Dataset
venn_list_gse[[1]] <- res_gse[[2]][res_gse[[2]]$P.value.adj < 0.05, ]$GeneSet
venn_list_gse[[2]] <- res_gse[[3]][res_gse[[3]]$P.value.adj < 0.05, ]$GeneSet

venn_list_deg <- vector("list", length = 2)
names(venn_list_deg) <- res$Dataset
venn_list_deg[[1]] <- res_deg[[2]][res_deg[[2]]$P.value.adj < 0.05, ]$Gene
venn_list_deg[[2]] <- res_deg[[3]][res_deg[[3]]$P.value.adj < 0.05, ]$Gene
```

Network Analysis
===

Row {.tabset}
---

### Upregulated in Tangle-bearing Neurons

```{r}
shinyApp(

  ui = fluidPage(
    fluidRow(
      column(
        width = 2,
        sliderInput(
          paste0("conn_up", 23),
          label = "Stringency:",
          min = 0,
          max = 1,
          value = 0.9,
          step = 0.1
        ),
      ),
      column(
        width = 2,
        radioButtons(
          paste0("shared_up", 23), label = NULL,
          c("All Features", "Shared Features Only"), inline = TRUE
        ),
        style = "padding-top: 35px;"
      ),
      column(
        width = 2,
        radioButtons(
          paste0("comp_up", 23), label = NULL,
          c("All Networks", "Main Network Only"), inline = TRUE
        ),
        style = "padding-top: 35px;"
      ),
      column(
        width = 2,
        sliderInput(
          paste0("degree_up", 23),
          label = "Connectivity:",
          min = 0,
          max = 1,
          value = 0.9,
          step = 0.1
        ),
      )
    ),
    fluidPage(
      div(
        style = "display:flex;",
        visNetworkOutput(paste0("vis_up", 23), height = "650px", width = "57%"),
        visNetworkOutput(paste0("vis2_up", 23), height = "650px", width = "43%")
      )
    )
  ),

  server = function (input, output, session) {
    observeEvent({
      input[[paste0("conn_up", 23)]]
      input[[paste0("shared_up", 23)]]
      input[[paste0("comp_up", 23)]]
      input[[paste0("degree_up", 23)]]
    }, {

      inverse <- round(1 - input[[paste0("conn_up", 23)]], digits = 2)

      de_gse <- rownames(res_gse[[2]][res_gse[[2]]$P.value.adj < 0.05, ])
      up_gse <- rownames(res_gse[[2]][res_gse[[2]]$Coef > 0, ])
      de_deg <- rownames(res_deg[[2]][res_deg[[2]]$P.value.adj < 0.05, ])
      up_deg <- rownames(res_deg[[2]][res_deg[[2]]$Coef > 0, ])

      net_data <- melt(geneIds(gene_sets[names(gene_sets) %in% de_gse]))
      names(net_data)[1] <- "ensembl"
      names(net_data)[2] <- "gene_set"

      gene_anno_sub <- gene_anno[gene_anno$ensembl %in% net_data$ensembl, ]
      net_data <- left_join(net_data, gene_anno_sub, by = "ensembl")
      net_data$gse_direction <- ifelse(
        net_data$gene_set %in% up_gse, yes = "up", no = "down"
      )
      net_data$gene_DE <- ifelse(
        net_data$ensembl %in% de_deg, yes = "yes", no = "no"
      )
      net_data$gene_direction <- ifelse(
        net_data$ensembl %in% up_deg, yes = "up", no = "down"
      )
      net_data$dataset <- "LCM Mass Spec"

      remove <- which(net_data$gse_direction != net_data$gene_direction)
      net_data <- net_data[-remove, ]
      net_data <- net_data[net_data$gene_DE == "yes", ]

      net_data <- net_data[which(net_data$gse_direction == "up"), ]
      net_data2 <- net_data
      net_data2_orig <- net_data2

      de_gse <- rownames(res_gse[[3]][res_gse[[3]]$P.value.adj < 0.05, ])
      up_gse <- rownames(res_gse[[3]][res_gse[[3]]$Coef > 0, ])
      de_deg <- rownames(res_deg[[3]][res_deg[[3]]$P.value.adj < 0.05, ])
      up_deg <- rownames(res_deg[[3]][res_deg[[3]]$Coef > 0, ])

      net_data <- melt(geneIds(gene_sets[names(gene_sets) %in% de_gse]))
      names(net_data)[1] <- "ensembl"
      names(net_data)[2] <- "gene_set"

      gene_anno_sub <- gene_anno[gene_anno$ensembl %in% net_data$ensembl, ]
      net_data <- left_join(net_data, gene_anno_sub, by = "ensembl")
      net_data$gse_direction <- ifelse(
        net_data$gene_set %in% up_gse, yes = "up", no = "down"
      )
      net_data$gene_DE <- ifelse(
        net_data$ensembl %in% de_deg, yes = "yes", no = "no"
      )
      net_data$gene_direction <- ifelse(
        net_data$ensembl %in% up_deg, yes = "up", no = "down"
      )
      net_data$dataset <- "FACS ssRNAseq"

      remove <- which(net_data$gse_direction != net_data$gene_direction)
      net_data <- net_data[-remove, ]
      net_data <- net_data[net_data$gene_DE == "yes", ]

      net_data <- net_data[which(net_data$gse_direction == "up"), ]
      net_data3 <- net_data
      net_data3_orig <- net_data3

      net_data <- rbind(net_data2, net_data3)
      net_data_table2 <- table(net_data2$symbol)
      net_data_table3 <- table(net_data3$symbol)

      gene_sets_sub <- gene_sets[names(gene_sets) %in% rownames(gse[[2]])]
      gene_sets_table2 <- table(unlist(geneIds(gene_sets_sub)))
      gene_sets_sub <- gene_sets[names(gene_sets) %in% rownames(gse[[3]])]
      gene_sets_table3 <- table(unlist(geneIds(gene_sets_sub)))

      gene_anno_sub <- gene_anno[
        gene_anno$ensembl %in% names(gene_sets_table2),
      ]
      gene_anno_sub <- gene_anno_sub[
        match(names(gene_sets_table2), gene_anno_sub$ensembl),
      ]
      names(gene_sets_table2) <- gene_anno_sub$symbol

      gene_anno_sub <- gene_anno[
        gene_anno$ensembl %in% names(gene_sets_table3),
      ]
      gene_anno_sub <- gene_anno_sub[
        match(names(gene_sets_table3), gene_anno_sub$ensembl),
      ]
      names(gene_sets_table3) <- gene_anno_sub$symbol

      gene_sets_table2 <- gene_sets_table2[
        names(gene_sets_table2) %in% names(net_data_table2)
      ]
      gene_sets_table3 <- gene_sets_table3[
        names(gene_sets_table3) %in% names(net_data_table3)
      ]
      gene_sets_table2 <- gene_sets_table2[
        match(names(net_data_table2), names(gene_sets_table2))
      ]
      gene_sets_table3 <- gene_sets_table3[
        match(names(net_data_table3), names(gene_sets_table3))
      ]

      pval2 <- res_deg[[2]]
      pval2 <- pval2[pval2$Gene %in% names(net_data_table2), ]
      pval2 <- pval2[match(names(net_data_table2), pval2$Gene), ]
      pval2 <- pval2$Coef
      pval2 <- (pval2 - min(pval2)) / (max(pval2) - min(pval2))
      pval2 <- rank(pval2)
      pval2 <- ((pval2 - min(pval2)) / (max(pval2) - min(pval2))) / 100000000000
      names(pval2) <- names(net_data_table2)

      pval3 <- res_deg[[3]]
      pval3 <- pval3[pval3$Gene %in% names(net_data_table3), ]
      pval3 <- pval3[match(names(net_data_table3), pval3$Gene), ]
      pval3 <- pval3$Coef
      pval3 <- (pval3 - min(pval3)) / (max(pval3) - min(pval3))
      pval3 <- rank(pval3)
      pval3 <- ((pval3 - min(pval3)) / (max(pval3) - min(pval3))) / 100000000000
      names(pval3) <- names(net_data_table3)

      dup2 <- c()
      for (gene in unique(net_data2$symbol)) {
        matched_gse <- net_data2[net_data2$symbol %in% gene, ]$gene_set
        net_data_sub <- net_data2[net_data2$gene_set %in% matched_gse, ]
        net_data_sub <- net_data_sub[net_data_sub$symbol %notin% gene, ]
        dup_table <- table(net_data_sub$symbol)
        if (length(dup_table) > 0) {
          dup2 <- c(dup2, mean(dup_table))
        } else {
          dup2 <- c(dup2, 1)
        }
      }
      names(dup2) <- unique(net_data2$symbol)
      dup2 <- dup2[match(names(net_data_table2), names(dup2))]

      dup3 <- c()
      set_size3 <- c()
      for (gene in unique(net_data3$symbol)) {
        matched_gse <- net_data3[net_data3$symbol %in% gene, ]$gene_set
        net_data_sub <- net_data3[net_data3$gene_set %in% matched_gse, ]
        net_data_sub <- net_data_sub[net_data_sub$symbol %notin% gene, ]
        dup_table <- table(net_data_sub$symbol)
        if (length(dup_table) > 0) {
          dup3 <- c(dup3, mean(dup_table))
        } else {
          dup3 <- c(dup3, 1)
        }
      }
      names(dup3) <- unique(net_data3$symbol)
      dup3 <- dup3[match(names(net_data_table3), names(dup3))]

      net_data_table2 <- (
        ((net_data_table2 / gene_sets_table2) * net_data_table2) / dup2
      ) + pval2
      net_data_table3 <- (
        ((net_data_table3 / gene_sets_table3) * net_data_table3) / dup3
      ) + pval3
      net_data_table2_scaled <- net_data_table2
      net_data_table3_scaled <- net_data_table3
      net_data_table2_scaled <- rank(net_data_table2_scaled)
      net_data_table3_scaled <- rank(net_data_table3_scaled)
      net_data_table2_scaled <- (
        (net_data_table2_scaled - min(net_data_table2_scaled)) /
          (max(net_data_table2_scaled) - min(net_data_table2_scaled))
      )
      net_data_table3_scaled <- (
        (net_data_table3_scaled - min(net_data_table3_scaled)) /
          (max(net_data_table3_scaled) - min(net_data_table3_scaled))
      )

      keep2 <- net_data_table2_scaled[
        net_data_table2_scaled > (
          inverse * ((length(net_data_table2) / length(net_data_table3)) * 1)
        ) + ((length(net_data_table2) / length(net_data_table3)) * 1)
      ]
      net_data2 <- net_data2[net_data2$symbol %in% names(keep2), ]

      hub_mat <- as.data.frame.matrix(table(net_data2[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )

      degree <- degree(graph)
      degree2 <- degree

      hub_mat <- as.data.frame.matrix(table(net_data2[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )
      graph <- subgraph(graph, which(degree(graph) > 0))

      keep2 <- c()
      for (i in seq_along(V(graph))) {
        neighbors <- c(V(graph)[i], neighbors(graph, V(graph)[i]))
        net_data_table_sub <- net_data_table2[
          names(net_data_table2) %in% names(neighbors)
        ]
        keep2 <- c(
          keep2,
          names(net_data_table_sub)[
            which(net_data_table_sub == max(net_data_table_sub))
          ]
        )
      }
      keep2_table <- table(keep2)
      keep2_ref <- c()
      for (name in names(keep2_table)) {
        neighbors <- c(
          V(graph)$name[which(V(graph)$name == name)],
          names(neighbors(graph, V(graph)$name[which(V(graph)$name == name)]))
        )
        keep2_ref <- c(keep2_ref, length(neighbors))
      }
      degree_sub <- degree2[names(degree2) %in% names(keep2_table)]
      degree_sub <- (keep2_table / degree_sub)
      keep2_table <- (keep2_table / keep2_ref)
      net_data_table_sub <- net_data_table2[
        names(net_data_table2) %in% names(keep2_table)
      ]
      keep2_table <- net_data_table_sub * keep2_table * degree_sub
      keep2_table_unscaled <- keep2_table
      if (length(keep2_table) > 1) {
        keep2_table <- rank(keep2_table)
        keep2_table <- (
          (keep2_table - min(keep2_table)) /
            (max(keep2_table) - min(keep2_table))
        )
      } else {
        keep2_table <- 1
      }
      if (length(keep2_table) > 1) {
        keep2 <- names(keep2_table)[
          keep2_table > network_filt(input[[paste0("conn_up", 23)]])[[1]]
        ]
      } else {
        keep2 <- names(keep2_table)
      }

      keep3 <- net_data_table3_scaled[
        net_data_table3_scaled > (
          input[[paste0("conn_up", 23)]] *
            ((length(net_data_table2) / length(net_data_table3)) * 1)
        ) +
          1 - ((length(net_data_table2) / length(net_data_table3)) * 1)
      ]
      net_data3 <- net_data3[net_data3$symbol %in% names(keep3), ]

      hub_mat <- as.data.frame.matrix(table(net_data3[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )

      degree <- degree(graph)
      degree3 <- degree

      hub_mat <- as.data.frame.matrix(table(net_data3[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )
      graph <- subgraph(graph, which(degree(graph) > 0))

      keep3 <- c()
      for (i in seq_along(V(graph))) {
        neighbors <- c(V(graph)[i], neighbors(graph, V(graph)[i]))
        net_data_table_sub <- net_data_table3[
          names(net_data_table3) %in% names(neighbors)
        ]
        keep3 <- c(
          keep3,
          names(net_data_table_sub)[
            which(net_data_table_sub == max(net_data_table_sub))
          ]
        )
      }
      keep3_table <- table(keep3)
      keep3_ref <- c()
      for (name in names(keep3_table)) {
        neighbors <- c(
          V(graph)$name[which(V(graph)$name == name)],
          names(neighbors(graph, V(graph)$name[which(V(graph)$name == name)]))
        )
        keep3_ref <- c(keep3_ref, length(neighbors))
      }
      degree_sub <- degree3[names(degree3) %in% names(keep3_table)]
      degree_sub <- (keep3_table / degree_sub)
      keep3_table <- (keep3_table / keep3_ref)
      net_data_table_sub <- net_data_table3[
        names(net_data_table3) %in% names(keep3_table)
      ]
      keep3_table <- net_data_table_sub * keep3_table * degree_sub
      keep3_table_unscaled <- keep3_table
      if (length(keep3_table) > 1) {
        keep3_table <- rank(keep3_table)
        keep3_table <- (
          (keep3_table - min(keep3_table)) /
            (max(keep3_table) - min(keep3_table))
        )
      } else {
        keep3_table <- 1
      }
      if (length(keep3_table) > 1) {
        keep3 <- names(keep3_table)[
          keep3_table > network_filt(input[[paste0("conn_up", 23)]])[[2]]
        ]
      } else {
        keep3 <- names(keep3_table)
      }

      if (input[[paste0("shared_up", 23)]] == "Shared Features Only") {
        net_data <- net_data[
          net_data$symbol %in% net_data2_orig$symbol &
            net_data$symbol %in% net_data3_orig$symbol,
        ]
      } else {
        net_data <- net_data[
          net_data$symbol %in% net_data2$symbol |
            net_data$symbol %in% net_data3$symbol,
        ]
      }

      hub_mat <- as.data.frame.matrix(table(net_data[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )

      keep_idx <- which(V(graph)$name %in% c(keep2, keep3))
      keep_degree <- unique(
        unlist(
          neighborhood(graph, order = map_range(inverse), nodes = keep_idx)
        )
      )
      keep_degree <- unique(c(keep_idx, keep_degree))
      graph <- induced_subgraph(graph, vids = keep_degree)

      if (input[[paste0("shared_up", 23)]] == "All Features") {
        graph <- subgraph(graph, which(degree(graph) > 0))
      }

      if (input[[paste0("comp_up", 23)]] == "Main Network Only") {
        graph <- subgraph(graph, which(components(graph)$membership == 1))
      }

      edges <- get.edgelist(graph, names = FALSE)
      layout <- qgraph.layout.fruchtermanreingold(
        edges, vcount = vcount(graph), weights = E(graph)$weight,
        area = vcount(graph), repulse.rad = vcount(graph) / 4
      )
      vis <- toVisNetworkData(graph)

      net_data_nodup <- net_data[-which(duplicated(net_data$symbol)), ]
      net_data_nodup <- net_data_nodup[
        net_data_nodup$symbol %in% vis$nodes$id,
      ]
      net_data_nodup <- net_data_nodup[
        match(vis$nodes$id, net_data_nodup$symbol),
      ]
      vis$nodes$shape <- ifelse(
        net_data_nodup$symbol %in% c(keep2, keep3), yes = "circle", no = "box"
      )

      keep2_table <- keep2_table[names(keep2_table) %in% keep2]
      keep3_table <- keep3_table[names(keep3_table) %in% keep3]
      keep_table_comb <- c(keep2_table, keep3_table)
      keep_table_comb <- keep_table_comb[
        names(keep_table_comb) %in% vis$nodes$id
      ]
      if (length(keep_table_comb) > 1 & all(keep_table_comb != 1)) {
        keep_table_comb <- (
          (keep_table_comb - min(keep_table_comb)) /
            (max(keep_table_comb) - min(keep_table_comb))
        )
      } else if (length(keep_table_comb) == 1) {
        keep_table_comb <- 1
      }
      size <- c()
      for (gene in vis$nodes$id) {
        if (gene %in% names(keep_table_comb)) {
          keep_table_sub <- keep_table_comb[names(keep_table_comb) %in% gene]
          if (length(keep_table_sub > 0)) {
            keep_table_sub <- sum(keep_table_sub)
          }
          keep_table_sub <- (((keep_table_sub + 2) ^ 6) / 8) + 22
          size <- c(size, keep_table_sub)
        } else {
          size <- c(size, 30)
        }
      }
      vis$nodes$size <- size
      vis$edges$width <- (vis$edges$weight + 0) ^ 1.25

      if (length(names(V(graph))) > 0) {
        col <- case_when(
          names(V(graph)) %in% net_data2_orig$symbol &
            names(V(graph)) %in% net_data3_orig$symbol ~ "green",
          names(V(graph)) %in% net_data2_orig$symbol ~ "yellow",
          names(V(graph)) %in% net_data3_orig$symbol ~ "orange"
        )
        vis$nodes$group <- col

        f <- pmax((max(nchar(vis$nodes$id)) - nchar(vis$nodes$id)) / 2, 0)
        vis$nodes$label <- sprintf(
          "%-*s%s%*s", f, "", vis$nodes$id, ceiling(f), ""
        )
        vis$nodes$font.size <- vis$nodes$size

        title <- vector(length = length(vis$nodes$id))
        for (j in seq_along(title)) {
          net_data_sub <- net_data[net_data$symbol == vis$nodes$id[j], ]
          title[j] <- paste0(
            net_data_sub$gene_set, " - ",
            net_data_sub$dataset, collapse = "<br>"
          )
        }
        vis$nodes$title <- title

        vis <- visNetwork(vis$nodes, vis$edges, background = "black")
        vis <- visPhysics(vis, stabilization = FALSE)
        vis <- visEdges(
          vis, smooth = FALSE, color = list(opacity = 0.8, inherit = "both")
        )
        vis <- visIgraphLayout(
          vis, layout = "layout.norm", layoutMatrix = layout
        )
        vis <- visOptions(
          vis,
          highlightNearest = list(
            enabled = TRUE,
            degree = ifelse(
              map_range(inverse) - 1 < 1, yes = 1, no = map_range(inverse) - 1
            )
          ),
          nodesIdSelection = TRUE
        )
        vis <- visNodes(vis, font = list(color = "white"))
        vis <- visGroups(
          vis,
          groupname = "green",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(0, 255, 0, 1)",
            highlight = list(
              background = "rgba(0, 255, 0, 0.5)",
              border = "rgba(0, 255, 0, 1)"
            )
          )
        )
        vis <- visGroups(
          vis,
          groupname = "yellow",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 255, 0, 1)",
            highlight = list(
              background = "rgba(255, 255, 0, 0.5)",
              border = "rgba(255, 255, 0, 1)"
            )
          )
        )
        vis <- visGroups(
          vis,
          groupname = "orange",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 165, 0, 1)",
            highlight = list(
              background = "rgba(255, 165, 0, 0.5)",
              border = "rgba(255, 165, 0, 1)"
            )
          )
        )
        vis <- visInteraction(
          vis,
          tooltipStyle =
            "width: max-content;position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #ffffff;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);opacity: 1;"
        )
        lnodes <- data.frame(
          label = c(
            "Upregulated\nGenes/Proteins/\nPathways\n\nLegend",
            "Differentially\nExpressed",
            "Network\nHub",
            "LCM\nMass Spec",
            "FACS\nssRNAseq",
            "Both\nDatasets"
          ),
          color.background = c(
            "black", "black", "black", "black", "black", "black"
          ),
          color.border = c(
            "rgba(255, 255, 255, 1)", "rgba(255, 255, 255, 1)",
            "rgba(255, 255, 255, 1)", "rgba(255, 255, 0, 1)",
            "rgba(255, 165, 0, 1)", "rgba(0, 255, 0, 1)"
          ),
          shape = c("text", "box", "circle", "ellipse", "ellipse", "ellipse"),
          font.color = "white",
          font.size = c(15, 12, 12, 12, 12, 12)
        )
        vis <- visLegend(
          vis, addNodes = lnodes, position = "right",
          useGroups = FALSE, stepY = 60, zoom = FALSE
        )
      }
      output$vis_up23 <- renderVisNetwork({vis})

      net_data <- net_data[net_data$symbol %in% c(keep2, keep3), ]
      vertices <- data.frame(
        name = c(unique(net_data$symbol), unique(net_data$gene_set)),
        type = c(
          rep("deg", length(unique(net_data$symbol))),
          rep("gse", length(unique(net_data$gene_set)))
        )
      )
      edges <- as.data.frame(as.matrix(net_data[ , c(3, 2)]))
      colnames(edges) <- c("from", "to")

      graph <- graph_from_data_frame(
        edges, vertices = vertices, directed = FALSE
      )

      keep_idx <- which(V(graph)$name %in% c(keep2, keep3))
      keep_degree <- unique(
        unlist(
          neighborhood(graph, order = map_range(inverse), nodes = keep_idx)
        )
      )
      keep_degree <- unique(c(keep_idx, keep_degree))
      graph <- induced_subgraph(graph, vids = keep_degree)

      graph <- subgraph(graph, which(degree(graph) > 0))

      graph_sub <- V(graph)[which(V(graph)$type == "gse")]
      degree <- degree(graph, v = graph_sub)

      pval2 <- res_gse[[2]]
      pval2 <- pval2[pval2$GeneSet %in% names(degree), ]
      degree_sub <- degree[names(degree) %in% pval2$GeneSet]
      pval2 <- pval2[match(names(degree_sub), pval2$GeneSet), ]
      pval2 <- pval2$Coef
      names(pval2) <- names(degree_sub)

      pval3 <- res_gse[[3]]
      pval3 <- pval3[pval3$GeneSet %in% names(degree), ]
      degree_sub <- degree[names(degree) %in% pval3$GeneSet]
      pval3 <- pval3[match(names(degree_sub), pval3$GeneSet), ]
      pval3 <- pval3$Coef
      names(pval3) <- names(degree_sub)

      pval <- c(pval2, pval3)
      pval <- tapply(pval, INDEX = names(pval), FUN = sum)
      pval <- pval[match(names(degree), names(pval))]
      pval <- (pval - min(pval)) / (max(pval) - min(pval))
      pval <- rank(pval)
      pval <- ((pval - min(pval)) / (max(pval) - min(pval))) / 100000000000

      degree <- degree + pval
      degree <- (degree - min(degree)) / (max(degree) - min(degree))
      degree <- rank(degree)
      degree <- (degree - min(degree)) / (max(degree) - min(degree))

      graph_sub <- graph_sub[degree >= input[[paste0("degree_up", 23)]]]
      graph <- induced_subgraph(
        graph, vids = unlist(neighborhood(graph, order = 1, nodes = graph_sub))
      )

      edge_counts <- table(
        apply(
          get.edgelist(graph), MARGIN = 1,
          FUN = function(x) paste(sort(x), collapse = "-")
        )
      )
      E(graph)$weight <- edge_counts[
        apply(
          get.edgelist(graph), MARGIN = 1,
          FUN = function(x) paste(sort(x), collapse = "-")
        )
      ]
      edges <- get.edgelist(graph, names = FALSE)
      layout <- qgraph.layout.fruchtermanreingold(
        edges, vcount = vcount(graph), weights = E(graph)$weight,
        area = vcount(graph), repulse.rad = vcount(graph) / 4
      )
      vis2 <- toVisNetworkData(graph)

      vis2$nodes$shape <- ifelse(
        vis2$nodes$id %in% c(keep2, keep3), yes = "circle", no = "box"
      )

      keep2_table <- keep2_table[names(keep2_table) %in% keep2]
      keep3_table <- keep3_table[names(keep3_table) %in% keep3]
      keep_table_comb <- c(keep2_table, keep3_table)
      keep_table_comb <- keep_table_comb[
        names(keep_table_comb) %in% vis2$nodes$id
      ]
      if (length(keep_table_comb) > 1 & all(keep_table_comb != 1)) {
        keep_table_comb <- (
          (keep_table_comb - min(keep_table_comb)) /
            (max(keep_table_comb) - min(keep_table_comb))
        )
      } else if (length(keep_table_comb) == 1) {
        keep_table_comb <- 1
      }
      size <- c()
      for (gene in vis2$nodes$id) {
        if (gene %in% names(keep_table_comb)) {
          keep_table_sub <- keep_table_comb[names(keep_table_comb) %in% gene]
          if (length(keep_table_sub > 0)) {
            keep_table_sub <- sum(keep_table_sub)
          }
          keep_table_sub <- (((keep_table_sub + 2) ^ 6) / 16) + 11
          size <- c(size, keep_table_sub)
        } else {
          size <- c(size, 35)
        }
      }
      vis2$nodes$size <- size
      vis2$edges$width <- (vis2$edges$weight + 0.5) ^ 3.5

      if (length(names(V(graph))) > 0) {
        col <- case_when(
          names(V(graph)) %in% net_data2_orig$symbol &
            names(V(graph)) %in% net_data3_orig$symbol ~ "green",
          names(V(graph)) %in% net_data2_orig$symbol ~ "yellow",
          names(V(graph)) %in% net_data3_orig$symbol ~ "orange",
          names(V(graph)) %in% net_data2_orig$gene_set &
            names(V(graph)) %in% net_data3_orig$gene_set ~ "green",
          names(V(graph)) %in% net_data2_orig$gene_set ~ "yellow",
          names(V(graph)) %in% net_data3_orig$gene_set ~ "orange"
        )
        vis2$nodes$group <- col

        deg_string <- vis2$nodes$id[vis2$nodes$id %in% net_data$symbol]
        f <- pmax((max(nchar(net_data$symbol)) - nchar(deg_string)) / 2, 0)
        deg_string <- sprintf(
          "%-*s%s%*s", f, "", deg_string, ceiling(f), ""
        )
        gse_string <- vis2$nodes$id[vis2$nodes$id %in% net_data$gene_set]
        gse_string <- sapply(gse_string, FUN = add_newline)
        vis2$nodes$label <- c(deg_string, gse_string)
        vis2$nodes$font.size <- vis2$nodes$size

        vis2 <- visNetwork(vis2$nodes, vis2$edges, background = "black")
        vis2 <- visPhysics(vis2, stabilization = FALSE)
        vis2 <- visEdges(
          vis2, smooth = FALSE, color = list(opacity = 0.8, inherit = "both")
        )
        vis2 <- visIgraphLayout(
          vis2, layout = "layout.norm", layoutMatrix = layout
        )
        vis2 <- visOptions(
          vis2,
          highlightNearest = list(
            enabled = TRUE,
            degree = ifelse(
              map_range(inverse) - 1 < 1, yes = 1, no = map_range(inverse) - 1
            )
          ),
          nodesIdSelection = TRUE
        )
        vis2 <- visNodes(vis2, font = list(color = "white"))
        vis2 <- visGroups(
          vis2,
          groupname = "green",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(0, 255, 0, 1)",
            highlight = list(
              background = "rgba(0, 255, 0, 0.5)",
              border = "rgba(0, 255, 0, 1)"
            )
          )
        )
        vis2 <- visGroups(
          vis2,
          groupname = "yellow",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 255, 0, 1)",
            highlight = list(
              background = "rgba(255, 255, 0, 0.5)",
              border = "rgba(255, 255, 0, 1)"
            )
          )
        )
        vis2 <- visGroups(
          vis2,
          groupname = "orange",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 165, 0, 1)",
            highlight = list(
              background = "rgba(255, 165, 0, 0.5)",
              border = "rgba(255, 165, 0, 1)"
            )
          )
        )
      }
      output$vis2_up23 <- renderVisNetwork({vis2})

    })
  }
)
```

### Downregulated in Tangle-bearing Neurons

```{r}
shinyApp(

  ui = fluidPage(
    fluidRow(
      column(
        width = 2,
        sliderInput(
          paste0("conn_dn", 23),
          label = "Stringency:",
          min = 0,
          max = 1,
          value = 0.1,
          step = 0.1
        ),
      ),
      column(
        width = 2,
        radioButtons(
          paste0("shared_dn", 23), label = NULL,
          c("All Features", "Shared Features Only"), inline = TRUE
        ),
        style = "padding-top: 35px;"
      ),
      column(
        width = 2,
        radioButtons(
          paste0("comp_dn", 23), label = NULL,
          c("All Networks", "Main Network Only"), inline = TRUE
        ),
        style = "padding-top: 35px;"
      ),
      column(
        width = 2,
        sliderInput(
          paste0("degree_dn", 23),
          label = "Connectivity:",
          min = 0,
          max = 1,
          value = 0.1,
          step = 0.1
        ),
      )
    ),
    fluidPage(
      div(
        style = "display:flex;",
        visNetworkOutput(paste0("vis_dn", 23), height = "650px", width = "57%"),
        visNetworkOutput(paste0("vis2_dn", 23), height = "650px", width = "43%")
      )
    )
  ),

  server = function (input, output, session) {
    observeEvent({
      input[[paste0("conn_dn", 23)]]
      input[[paste0("shared_dn", 23)]]
      input[[paste0("comp_dn", 23)]]
      input[[paste0("degree_dn", 23)]]
    }, {

      inverse <- round(1 - input[[paste0("conn_dn", 23)]], digits = 2)

      de_gse <- rownames(res_gse[[2]][res_gse[[2]]$P.value.adj < 0.05, ])
      up_gse <- rownames(res_gse[[2]][res_gse[[2]]$Coef > 0, ])
      de_deg <- rownames(res_deg[[2]][res_deg[[2]]$P.value.adj < 0.05, ])
      up_deg <- rownames(res_deg[[2]][res_deg[[2]]$Coef > 0, ])

      net_data <- melt(geneIds(gene_sets[names(gene_sets) %in% de_gse]))
      names(net_data)[1] <- "ensembl"
      names(net_data)[2] <- "gene_set"

      gene_anno_sub <- gene_anno[gene_anno$ensembl %in% net_data$ensembl, ]
      net_data <- left_join(net_data, gene_anno_sub, by = "ensembl")
      net_data$gse_direction <- ifelse(
        net_data$gene_set %in% up_gse, yes = "up", no = "down"
      )
      net_data$gene_DE <- ifelse(
        net_data$ensembl %in% de_deg, yes = "yes", no = "no"
      )
      net_data$gene_direction <- ifelse(
        net_data$ensembl %in% up_deg, yes = "up", no = "down"
      )
      net_data$dataset <- "LCM Mass Spec"

      remove <- which(net_data$gse_direction != net_data$gene_direction)
      net_data <- net_data[-remove, ]
      net_data <- net_data[net_data$gene_DE == "yes", ]

      net_data <- net_data[which(net_data$gse_direction == "down"), ]
      net_data2 <- net_data
      net_data2_orig <- net_data2

      de_gse <- rownames(res_gse[[3]][res_gse[[3]]$P.value.adj < 0.05, ])
      up_gse <- rownames(res_gse[[3]][res_gse[[3]]$Coef > 0, ])
      de_deg <- rownames(res_deg[[3]][res_deg[[3]]$P.value.adj < 0.05, ])
      up_deg <- rownames(res_deg[[3]][res_deg[[3]]$Coef > 0, ])

      net_data <- melt(geneIds(gene_sets[names(gene_sets) %in% de_gse]))
      names(net_data)[1] <- "ensembl"
      names(net_data)[2] <- "gene_set"

      gene_anno_sub <- gene_anno[gene_anno$ensembl %in% net_data$ensembl, ]
      net_data <- left_join(net_data, gene_anno_sub, by = "ensembl")
      net_data$gse_direction <- ifelse(
        net_data$gene_set %in% up_gse, yes = "up", no = "down"
      )
      net_data$gene_DE <- ifelse(
        net_data$ensembl %in% de_deg, yes = "yes", no = "no"
      )
      net_data$gene_direction <- ifelse(
        net_data$ensembl %in% up_deg, yes = "up", no = "down"
      )
      net_data$dataset <- "FACS ssRNAseq"

      remove <- which(net_data$gse_direction != net_data$gene_direction)
      net_data <- net_data[-remove, ]
      net_data <- net_data[net_data$gene_DE == "yes", ]

      net_data <- net_data[which(net_data$gse_direction == "down"), ]
      net_data3 <- net_data
      net_data3_orig <- net_data3

      net_data <- rbind(net_data2, net_data3)
      net_data_table2 <- table(net_data2$symbol)
      net_data_table3 <- table(net_data3$symbol)

      gene_sets_sub <- gene_sets[names(gene_sets) %in% rownames(gse[[2]])]
      gene_sets_table2 <- table(unlist(geneIds(gene_sets_sub)))
      gene_sets_sub <- gene_sets[names(gene_sets) %in% rownames(gse[[3]])]
      gene_sets_table3 <- table(unlist(geneIds(gene_sets_sub)))

      gene_anno_sub <- gene_anno[
        gene_anno$ensembl %in% names(gene_sets_table2),
      ]
      gene_anno_sub <- gene_anno_sub[
        match(names(gene_sets_table2), gene_anno_sub$ensembl),
      ]
      names(gene_sets_table2) <- gene_anno_sub$symbol

      gene_anno_sub <- gene_anno[
        gene_anno$ensembl %in% names(gene_sets_table3),
      ]
      gene_anno_sub <- gene_anno_sub[
        match(names(gene_sets_table3), gene_anno_sub$ensembl),
      ]
      names(gene_sets_table3) <- gene_anno_sub$symbol

      gene_sets_table2 <- gene_sets_table2[
        names(gene_sets_table2) %in% names(net_data_table2)
      ]
      gene_sets_table3 <- gene_sets_table3[
        names(gene_sets_table3) %in% names(net_data_table3)
      ]
      gene_sets_table2 <- gene_sets_table2[
        match(names(net_data_table2), names(gene_sets_table2))
      ]
      gene_sets_table3 <- gene_sets_table3[
        match(names(net_data_table3), names(gene_sets_table3))
      ]

      pval2 <- res_deg[[2]]
      pval2 <- pval2[pval2$Gene %in% names(net_data_table2), ]
      pval2 <- pval2[match(names(net_data_table2), pval2$Gene), ]
      pval2 <- pval2$Coef
      pval2 <- (pval2 - min(pval2)) / (max(pval2) - min(pval2))
      pval2 <- rank(pval2)
      pval2 <- ((pval2 - min(pval2)) / (max(pval2) - min(pval2))) / 100000000000
      names(pval2) <- names(net_data_table2)

      pval3 <- res_deg[[3]]
      pval3 <- pval3[pval3$Gene %in% names(net_data_table3), ]
      pval3 <- pval3[match(names(net_data_table3), pval3$Gene), ]
      pval3 <- pval3$Coef
      pval3 <- (pval3 - min(pval3)) / (max(pval3) - min(pval3))
      pval3 <- rank(pval3)
      pval3 <- ((pval3 - min(pval3)) / (max(pval3) - min(pval3))) / 100000000000
      names(pval3) <- names(net_data_table3)

      dup2 <- c()
      for (gene in unique(net_data2$symbol)) {
        matched_gse <- net_data2[net_data2$symbol %in% gene, ]$gene_set
        net_data_sub <- net_data2[net_data2$gene_set %in% matched_gse, ]
        net_data_sub <- net_data_sub[net_data_sub$symbol %notin% gene, ]
        dup_table <- table(net_data_sub$symbol)
        if (length(dup_table) > 0) {
          dup2 <- c(dup2, mean(dup_table))
        } else {
          dup2 <- c(dup2, 1)
        }
      }
      names(dup2) <- unique(net_data2$symbol)
      dup2 <- dup2[match(names(net_data_table2), names(dup2))]

      dup3 <- c()
      set_size3 <- c()
      for (gene in unique(net_data3$symbol)) {
        matched_gse <- net_data3[net_data3$symbol %in% gene, ]$gene_set
        net_data_sub <- net_data3[net_data3$gene_set %in% matched_gse, ]
        net_data_sub <- net_data_sub[net_data_sub$symbol %notin% gene, ]
        dup_table <- table(net_data_sub$symbol)
        if (length(dup_table) > 0) {
          dup3 <- c(dup3, mean(dup_table))
        } else {
          dup3 <- c(dup3, 1)
        }
      }
      names(dup3) <- unique(net_data3$symbol)
      dup3 <- dup3[match(names(net_data_table3), names(dup3))]

      net_data_table2 <- (
        ((net_data_table2 / gene_sets_table2) * net_data_table2) / dup2
      ) + pval2
      net_data_table3 <- (
        ((net_data_table3 / gene_sets_table3) * net_data_table3) / dup3
      ) + pval3
      net_data_table2_scaled <- net_data_table2
      net_data_table3_scaled <- net_data_table3
      net_data_table2_scaled <- rank(net_data_table2_scaled)
      net_data_table3_scaled <- rank(net_data_table3_scaled)
      net_data_table2_scaled <- (
        (net_data_table2_scaled - min(net_data_table2_scaled)) /
          (max(net_data_table2_scaled) - min(net_data_table2_scaled))
      )
      net_data_table3_scaled <- (
        (net_data_table3_scaled - min(net_data_table3_scaled)) /
          (max(net_data_table3_scaled) - min(net_data_table3_scaled))
      )

      keep2 <- net_data_table2_scaled[
        net_data_table2_scaled > (
          inverse * ((length(net_data_table2) / length(net_data_table3)) * 1)
        ) + ((length(net_data_table2) / length(net_data_table3)) * 1)
      ]
      net_data2 <- net_data2[net_data2$symbol %in% names(keep2), ]

      hub_mat <- as.data.frame.matrix(table(net_data2[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )

      degree <- degree(graph)
      degree2 <- degree

      hub_mat <- as.data.frame.matrix(table(net_data2[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )
      graph <- subgraph(graph, which(degree(graph) > 0))

      keep2 <- c()
      for (i in seq_along(V(graph))) {
        neighbors <- c(V(graph)[i], neighbors(graph, V(graph)[i]))
        net_data_table_sub <- net_data_table2[
          names(net_data_table2) %in% names(neighbors)
        ]
        keep2 <- c(
          keep2,
          names(net_data_table_sub)[
            which(net_data_table_sub == max(net_data_table_sub))
          ]
        )
      }
      keep2_table <- table(keep2)
      keep2_ref <- c()
      for (name in names(keep2_table)) {
        neighbors <- c(
          V(graph)$name[which(V(graph)$name == name)],
          names(neighbors(graph, V(graph)$name[which(V(graph)$name == name)]))
        )
        keep2_ref <- c(keep2_ref, length(neighbors))
      }
      degree_sub <- degree2[names(degree2) %in% names(keep2_table)]
      degree_sub <- (keep2_table / degree_sub)
      keep2_table <- (keep2_table / keep2_ref)
      net_data_table_sub <- net_data_table2[
        names(net_data_table2) %in% names(keep2_table)
      ]
      keep2_table <- net_data_table_sub * keep2_table * degree_sub
      keep2_table_unscaled <- keep2_table
      if (length(keep2_table) > 1) {
        keep2_table <- rank(keep2_table)
        keep2_table <- (
          (keep2_table - min(keep2_table)) /
            (max(keep2_table) - min(keep2_table))
        )
      } else {
        keep2_table <- 1
      }
      if (length(keep2_table) > 1) {
        keep2 <- names(keep2_table)[
          keep2_table > network_filt(input[[paste0("conn_dn", 23)]])[[1]]
        ]
      } else {
        keep2 <- names(keep2_table)
      }

      keep3 <- net_data_table3_scaled[
        net_data_table3_scaled > (
          input[[paste0("conn_dn", 23)]] *
            ((length(net_data_table2) / length(net_data_table3)) * 1)
        ) +
          1 - ((length(net_data_table2) / length(net_data_table3)) * 1)
      ]
      net_data3 <- net_data3[net_data3$symbol %in% names(keep3), ]

      hub_mat <- as.data.frame.matrix(table(net_data3[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )

      degree <- degree(graph)
      degree3 <- degree

      hub_mat <- as.data.frame.matrix(table(net_data3[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )
      graph <- subgraph(graph, which(degree(graph) > 0))

      keep3 <- c()
      for (i in seq_along(V(graph))) {
        neighbors <- c(V(graph)[i], neighbors(graph, V(graph)[i]))
        net_data_table_sub <- net_data_table3[
          names(net_data_table3) %in% names(neighbors)
        ]
        keep3 <- c(
          keep3,
          names(net_data_table_sub)[
            which(net_data_table_sub == max(net_data_table_sub))
          ]
        )
      }
      keep3_table <- table(keep3)
      keep3_ref <- c()
      for (name in names(keep3_table)) {
        neighbors <- c(
          V(graph)$name[which(V(graph)$name == name)],
          names(neighbors(graph, V(graph)$name[which(V(graph)$name == name)]))
        )
        keep3_ref <- c(keep3_ref, length(neighbors))
      }
      degree_sub <- degree3[names(degree3) %in% names(keep3_table)]
      degree_sub <- (keep3_table / degree_sub)
      keep3_table <- (keep3_table / keep3_ref)
      net_data_table_sub <- net_data_table3[
        names(net_data_table3) %in% names(keep3_table)
      ]
      keep3_table <- net_data_table_sub * keep3_table * degree_sub
      keep3_table_unscaled <- keep3_table
      if (length(keep3_table) > 1) {
        keep3_table <- rank(keep3_table)
        keep3_table <- (
          (keep3_table - min(keep3_table)) /
            (max(keep3_table) - min(keep3_table))
        )
      } else {
        keep3_table <- 1
      }
      if (length(keep3_table) > 1) {
        keep3 <- names(keep3_table)[
          keep3_table > network_filt(input[[paste0("conn_dn", 23)]])[[2]]
        ]
      } else {
        keep3 <- names(keep3_table)
      }

      if (input[[paste0("shared_dn", 23)]] == "Shared Features Only") {
        net_data <- net_data[
          net_data$symbol %in% net_data2_orig$symbol &
            net_data$symbol %in% net_data3_orig$symbol,
        ]
      } else {
        net_data <- net_data[
          net_data$symbol %in% net_data2$symbol |
            net_data$symbol %in% net_data3$symbol,
        ]
      }

      hub_mat <- as.data.frame.matrix(table(net_data[ , c(3, 2)]))
      hub_mat <- hub_mat == 1
      hub_mat <- hub_mat %*% t(hub_mat)
      diag(hub_mat) <- 0
      graph <- graph_from_adjacency_matrix(
        hub_mat, mode = "upper", weighted = TRUE
      )

      keep_idx <- which(V(graph)$name %in% c(keep2, keep3))
      keep_degree <- unique(
        unlist(
          neighborhood(graph, order = map_range(inverse), nodes = keep_idx)
        )
      )
      keep_degree <- unique(c(keep_idx, keep_degree))
      graph <- induced_subgraph(graph, vids = keep_degree)

      if (input[[paste0("shared_dn", 23)]] == "All Features") {
        graph <- subgraph(graph, which(degree(graph) > 0))
      }

      if (input[[paste0("comp_dn", 23)]] == "Main Network Only") {
        graph <- subgraph(graph, which(components(graph)$membership == 1))
      }

      edges <- get.edgelist(graph, names = FALSE)
      layout <- qgraph.layout.fruchtermanreingold(
        edges, vcount = vcount(graph), weights = E(graph)$weight,
        area = vcount(graph), repulse.rad = vcount(graph) / 4
      )
      vis <- toVisNetworkData(graph)

      net_data_nodup <- net_data[-which(duplicated(net_data$symbol)), ]
      net_data_nodup <- net_data_nodup[
        net_data_nodup$symbol %in% vis$nodes$id,
      ]
      net_data_nodup <- net_data_nodup[
        match(vis$nodes$id, net_data_nodup$symbol),
      ]
      vis$nodes$shape <- ifelse(
        net_data_nodup$symbol %in% c(keep2, keep3), yes = "circle", no = "box"
      )

      keep2_table <- keep2_table[names(keep2_table) %in% keep2]
      keep3_table <- keep3_table[names(keep3_table) %in% keep3]
      keep_table_comb <- c(keep2_table, keep3_table)
      keep_table_comb <- keep_table_comb[
        names(keep_table_comb) %in% vis$nodes$id
      ]
      if (length(keep_table_comb) > 1 & all(keep_table_comb != 1)) {
        keep_table_comb <- (
          (keep_table_comb - min(keep_table_comb)) /
            (max(keep_table_comb) - min(keep_table_comb))
        )
      } else if (length(keep_table_comb) == 1) {
        keep_table_comb <- 1
      }
      size <- c()
      for (gene in vis$nodes$id) {
        if (gene %in% names(keep_table_comb)) {
          keep_table_sub <- keep_table_comb[names(keep_table_comb) %in% gene]
          if (length(keep_table_sub > 0)) {
            keep_table_sub <- sum(keep_table_sub)
          }
          keep_table_sub <- (((keep_table_sub + 2) ^ 5) / 4) + 22
          size <- c(size, keep_table_sub)
        } else {
          size <- c(size, 30)
        }
      }
      vis$nodes$size <- size
      vis$edges$width <- (vis$edges$weight + 1) ^ 1.25

      if (length(names(V(graph))) > 0) {
        col <- case_when(
          names(V(graph)) %in% net_data2_orig$symbol &
            names(V(graph)) %in% net_data3_orig$symbol ~ "green",
          names(V(graph)) %in% net_data2_orig$symbol ~ "yellow",
          names(V(graph)) %in% net_data3_orig$symbol ~ "orange"
        )
        vis$nodes$group <- col

        f <- pmax((max(nchar(vis$nodes$id)) - nchar(vis$nodes$id)) / 2, 0)
        vis$nodes$label <- sprintf(
          "%-*s%s%*s", f, "", vis$nodes$id, ceiling(f), ""
        )
        vis$nodes$font.size <- vis$nodes$size

        title <- vector(length = length(vis$nodes$id))
        for (j in seq_along(title)) {
          net_data_sub <- net_data[net_data$symbol == vis$nodes$id[j], ]
          title[j] <- paste0(
            net_data_sub$gene_set, " - ",
            net_data_sub$dataset, collapse = "<br>"
          )
        }
        vis$nodes$title <- title

        vis <- visNetwork(vis$nodes, vis$edges, background = "black")
        vis <- visPhysics(vis, stabilization = FALSE)
        vis <- visEdges(
          vis, smooth = FALSE, color = list(opacity = 0.8, inherit = "both")
        )
        vis <- visIgraphLayout(
          vis, layout = "layout.norm", layoutMatrix = layout
        )
        vis <- visOptions(
          vis,
          highlightNearest = list(
            enabled = TRUE,
            degree = ifelse(
              map_range(inverse) - 1 < 1, yes = 1, no = map_range(inverse) - 1
            )
          ),
          nodesIdSelection = TRUE
        )
        vis <- visNodes(vis, font = list(color = "white"))
        vis <- visGroups(
          vis,
          groupname = "green",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(0, 255, 0, 1)",
            highlight = list(
              background = "rgba(0, 255, 0, 0.5)",
              border = "rgba(0, 255, 0, 1)"
            )
          )
        )
        vis <- visGroups(
          vis,
          groupname = "yellow",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 255, 0, 1)",
            highlight = list(
              background = "rgba(255, 255, 0, 0.5)",
              border = "rgba(255, 255, 0, 1)"
            )
          )
        )
        vis <- visGroups(
          vis,
          groupname = "orange",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 165, 0, 1)",
            highlight = list(
              background = "rgba(255, 165, 0, 0.5)",
              border = "rgba(255, 165, 0, 1)"
            )
          )
        )
        vis <- visInteraction(
          vis,
          tooltipStyle =
            "width: max-content;position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #ffffff;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);opacity: 1;"
        )
        lnodes <- data.frame(
          label = c(
            "Downregulated\nGenes/Proteins/\nPathways\n\nLegend",
            "Differentially\nExpressed",
            "Network\nHub",
            "LCM\nMass Spec",
            "FACS\nssRNAseq",
            "Both\nDatasets"
          ),
          color.background = c(
            "black", "black", "black", "black", "black", "black"
          ),
          color.border = c(
            "rgba(255, 255, 255, 1)", "rgba(255, 255, 255, 1)",
            "rgba(255, 255, 255, 1)", "rgba(255, 255, 0, 1)",
            "rgba(255, 165, 0, 1)", "rgba(0, 255, 0, 1)"
          ),
          shape = c("text", "box", "circle", "ellipse", "ellipse", "ellipse"),
          font.color = "white",
          font.size = c(15, 12, 12, 12, 12, 12)
        )
        vis <- visLegend(
          vis, addNodes = lnodes, position = "right",
          useGroups = FALSE, stepY = 60, zoom = FALSE
        )
      }
      output$vis_dn23 <- renderVisNetwork({vis})

      net_data <- net_data[net_data$symbol %in% c(keep2, keep3), ]
      vertices <- data.frame(
        name = c(unique(net_data$symbol), unique(net_data$gene_set)),
        type = c(
          rep("deg", length(unique(net_data$symbol))),
          rep("gse", length(unique(net_data$gene_set)))
        )
      )
      edges <- as.data.frame(as.matrix(net_data[ , c(3, 2)]))
      colnames(edges) <- c("from", "to")

      graph <- graph_from_data_frame(
        edges, vertices = vertices, directed = FALSE
      )

      keep_idx <- which(V(graph)$name %in% c(keep2, keep3))
      keep_degree <- unique(
        unlist(
          neighborhood(graph, order = map_range(inverse), nodes = keep_idx)
        )
      )
      keep_degree <- unique(c(keep_idx, keep_degree))
      graph <- induced_subgraph(graph, vids = keep_degree)

      graph <- subgraph(graph, which(degree(graph) > 0))

      graph_sub <- V(graph)[which(V(graph)$type == "gse")]
      degree <- degree(graph, v = graph_sub)

      pval2 <- res_gse[[2]]
      pval2 <- pval2[pval2$GeneSet %in% names(degree), ]
      degree_sub <- degree[names(degree) %in% pval2$GeneSet]
      pval2 <- pval2[match(names(degree_sub), pval2$GeneSet), ]
      pval2 <- pval2$Coef
      names(pval2) <- names(degree_sub)

      pval3 <- res_gse[[3]]
      pval3 <- pval3[pval3$GeneSet %in% names(degree), ]
      degree_sub <- degree[names(degree) %in% pval3$GeneSet]
      pval3 <- pval3[match(names(degree_sub), pval3$GeneSet), ]
      pval3 <- pval3$Coef
      names(pval3) <- names(degree_sub)

      pval <- c(pval2, pval3)
      pval <- tapply(pval, INDEX = names(pval), FUN = sum)
      pval <- pval[match(names(degree), names(pval))]
      pval <- (pval - min(pval)) / (max(pval) - min(pval))
      pval <- rank(pval)
      pval <- ((pval - min(pval)) / (max(pval) - min(pval))) / 100000000000

      degree <- degree + pval
      degree <- (degree - min(degree)) / (max(degree) - min(degree))
      degree <- rank(degree)
      degree <- (degree - min(degree)) / (max(degree) - min(degree))

      graph_sub <- graph_sub[degree >= input[[paste0("degree_dn", 23)]]]
      graph <- induced_subgraph(
        graph, vids = unlist(neighborhood(graph, order = 1, nodes = graph_sub))
      )

      edge_counts <- table(
        apply(
          get.edgelist(graph), MARGIN = 1,
          FUN = function(x) paste(sort(x), collapse = "-")
        )
      )
      E(graph)$weight <- edge_counts[
        apply(
          get.edgelist(graph), MARGIN = 1,
          FUN = function(x) paste(sort(x), collapse = "-")
        )
      ]
      edges <- get.edgelist(graph, names = FALSE)
      layout <- qgraph.layout.fruchtermanreingold(
        edges, vcount = vcount(graph), weights = E(graph)$weight,
        area = vcount(graph), repulse.rad = vcount(graph) / 4
      )
      vis2 <- toVisNetworkData(graph)

      vis2$nodes$shape <- ifelse(
        vis2$nodes$id %in% c(keep2, keep3), yes = "circle", no = "box"
      )

      keep2_table <- keep2_table[names(keep2_table) %in% keep2]
      keep3_table <- keep3_table[names(keep3_table) %in% keep3]
      keep_table_comb <- c(keep2_table, keep3_table)
      keep_table_comb <- keep_table_comb[
        names(keep_table_comb) %in% vis2$nodes$id
      ]
      if (length(keep_table_comb) > 1 & all(keep_table_comb != 1)) {
        keep_table_comb <- (
          (keep_table_comb - min(keep_table_comb)) /
            (max(keep_table_comb) - min(keep_table_comb))
        )
      } else if (length(keep_table_comb) == 1) {
        keep_table_comb <- 1
      }
      size <- c()
      for (gene in vis2$nodes$id) {
        if (gene %in% names(keep_table_comb)) {
          keep_table_sub <- keep_table_comb[names(keep_table_comb) %in% gene]
          if (length(keep_table_sub > 0)) {
            keep_table_sub <- sum(keep_table_sub)
          }
          keep_table_sub <- (((keep_table_sub + 2) ^ 6) / 16) + 11
          size <- c(size, keep_table_sub)
        } else {
          size <- c(size, 35)
        }
      }
      vis2$nodes$size <- size
      vis2$edges$width <- (vis2$edges$weight + 0.5) ^ 2

      if (length(names(V(graph))) > 0) {
        col <- case_when(
          names(V(graph)) %in% net_data2_orig$symbol &
            names(V(graph)) %in% net_data3_orig$symbol ~ "green",
          names(V(graph)) %in% net_data2_orig$symbol ~ "yellow",
          names(V(graph)) %in% net_data3_orig$symbol ~ "orange",
          names(V(graph)) %in% net_data2_orig$gene_set &
            names(V(graph)) %in% net_data3_orig$gene_set ~ "green",
          names(V(graph)) %in% net_data2_orig$gene_set ~ "yellow",
          names(V(graph)) %in% net_data3_orig$gene_set ~ "orange"
        )
        vis2$nodes$group <- col

        deg_string <- vis2$nodes$id[vis2$nodes$id %in% net_data$symbol]
        f <- pmax((max(nchar(net_data$symbol)) - nchar(deg_string)) / 2, 0)
        deg_string <- sprintf(
          "%-*s%s%*s", f, "", deg_string, ceiling(f), ""
        )
        gse_string <- vis2$nodes$id[vis2$nodes$id %in% net_data$gene_set]
        gse_string <- sapply(gse_string, FUN = add_newline)
        vis2$nodes$label <- c(deg_string, gse_string)
        vis2$nodes$font.size <- vis2$nodes$size

        vis2 <- visNetwork(vis2$nodes, vis2$edges, background = "black")
        vis2 <- visPhysics(vis2, stabilization = FALSE)
        vis2 <- visEdges(
          vis2, smooth = FALSE, color = list(opacity = 0.8, inherit = "both")
        )
        vis2 <- visIgraphLayout(
          vis2, layout = "layout.norm", layoutMatrix = layout
        )
        vis2 <- visOptions(
          vis2,
          highlightNearest = list(
            enabled = TRUE,
            degree = ifelse(
              map_range(inverse) - 1 < 1, yes = 1, no = map_range(inverse) - 1
            )
          ),
          nodesIdSelection = TRUE
        )
        vis2 <- visNodes(vis2, font = list(color = "white"))
        vis2 <- visGroups(
          vis2,
          groupname = "green",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(0, 255, 0, 1)",
            highlight = list(
              background = "rgba(0, 255, 0, 0.5)",
              border = "rgba(0, 255, 0, 1)"
            )
          )
        )
        vis2 <- visGroups(
          vis2,
          groupname = "yellow",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 255, 0, 1)",
            highlight = list(
              background = "rgba(255, 255, 0, 0.5)",
              border = "rgba(255, 255, 0, 1)"
            )
          )
        )
        vis2 <- visGroups(
          vis2,
          groupname = "orange",
          color = list(
            background = "rgba(0, 0, 0, 0.5)",
            border = "rgba(255, 165, 0, 1)",
            highlight = list(
              background = "rgba(255, 165, 0, 0.5)",
              border = "rgba(255, 165, 0, 1)"
            )
          )
        )
      }
      output$vis2_dn23 <- renderVisNetwork({vis2})

    })
  }
)
```

```{r, include = FALSE}
rm(
  deg, edges, gene_anno, gene_anno_sub, gene_sets, gene_sets_sub, graph, gse,
  hub_mat, layout, meta, n_deg, n_gse, net_data, net_data_nodup, net_data_sub,
  net_data2, net_data2_orig, net_data3, net_data3_orig, p_adj, range_deg,
  range_gse, res_deg, res_gse, res_gse_fmt, sig_deg, sig_gse, top_anno, top_deg,
  top_gse, vis, input, mat, sig, add, add_anno, mat2, mat3, sig2, sig3, add2,
  add3, add_anno2, add_anno3, gene_anno_sub2, gene_anno_sub3, gse_sub2,
  gene_ids2, links2, links_orig2, links_comb2, links_list2, nodes2, gse_sub3,
  gene_ids3, links3, links_orig3, links_comb3, links_list3, nodes3, deg_sub2,
  deg_sub3, mat2c, mat3c, sig2c, sig3c, add2c, add3c, add_anno2c, add_anno3c,
  gene_anno_sub2c, gene_anno_sub3c, df, hubs, pseudobulk_deg, n_gse, n_gse_up,
  n_gse_dn, n_deg, n_deg_up, n_deg_dn, res, venn_list_gse, venn_list_deg,
  vertices
)
gc()
```
